# Generated by Django 6.0.5 on 2026-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
