# Generated by Django 6.0.5 on 2026-06-25 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='product',
        ),
        migrations.AddField(
            model_name='media',
            name='product_variant',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productvariant'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
