# Generated by Django 6.0.5 on 2026-05-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecieverAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_first_name', models.CharField(max_length=100)),
                ('receiver_last_name', models.CharField(max_length=100)),
                ('receiver_phone_number', models.CharField(max_length=15)),
                ('receiver_gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('receiver_email', models.EmailField(max_length=254)),
                ('receiver_secondary_phone_number', models.CharField(max_length=15)),
                ('receiver_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('receiver_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('receiver_building', models.CharField(max_length=100)),
                ('receiver_floor', models.IntegerField()),
                ('receiver_directions', models.TextField()),
                ('receiver_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_number',
        ),
        migrations.AddField(
            model_name='order',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('failed_to_ship', 'Failed to Ship'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order.recieveraddress'),
        ),
    ]
