# Generated by Django 6.0.5 on 2026-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_recieveraddress_remove_order_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wakilni_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='barcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
