# Generated by Django 6.0.5 on 2026-06-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_wakilni_id_alter_order_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recieveraddress',
            name='receiver_latitude',
        ),
        migrations.RemoveField(
            model_name='recieveraddress',
            name='receiver_longitude',
        ),
    ]
